### ISSUE TITLE
Some features I think would be useful

### ISSUE THREAD

**Issue by Tyler3D** [AJS-development/client#2]
I have some ideas for the client. I think the ip 127.0.0.1 or localhost should automatically be able to use  
console commands in game. A chat??
A skin selector for names to long to fit in the <skin>
And a bar to type in your server ip.
Thanks

**Comment by LegitSoulja** [comment]
Well, everyone don't use localhost, so if you want to play on localhost you can do so, if not you still can do so with connecting

A chat I was also thinking about which would be a cool addon.

On start, you are given a prompt to enter your server connection info. There's really no other simple way of doing so.

A skin selector is also cool, but what about a select for the all the names in randomNames.txt from the game itself, and if a name is too long, then one of those will be given instead.
