### ISSUE TITLE
invalid protocol error

### ISSUE THREAD

**Issue by Barbosik** [AJS-development/client#5]
Just start MultiOgar server and connect to it with http://play.ogarul.tk/?ip=127.0.0.1:50000

Look at server warning in the chat:
```
WARNING Your client has protocol error!
Client sends invalid protocol version 1
Server assumes it as protocol 4
```

Could you please fix it?
Thanks

**Comment by Andrews54757** [comment]
multiogar is not supported

**Comment by Barbosik** [comment]
it's not related to MultiOgar. It's related to protocol.
The client doesn't comply with protocol.
Anyway it works well with MultiOgar. It's just detect that the client has an protocol error and sends notification about it

**Comment by Andrews54757** [comment]
It is because we change the protocals a bit as we add more features. We try to make it cross-version though

**Comment by LegitSoulja** [comment]
Why would we allow multiogar? OgarUl can expand 10x with new features we could be the best of them all. We don't have to follow protocols, as we are slowly making progress on our own protocol with new features. Cross version though eh I don't know. Our client can just be pure OgarUl servers only. I've been thinking about customizing the custom client just for only ogarul clients with site additions similar to the ads plugins and such, and implement coin system, and have unlock able skins and etc.
